
# Generated by Qodo Gen
import unittest
import tkinter as tk
from partner_connect.main import (load_questions, display_random_question)
import json
import os
import pytest

class TestLoadQuestions:

    # Successfully load questions from a valid JSON file
    def test_load_questions_success(self):
        # Create a temporary JSON file with sample data
        sample_data = [
            {
                "id": 1,
                "categorie": "Categorie1",
                "vraag": "Test questions number 1"
            },
            {
                "id": 2,
                "categorie": "Categorie2",
                "vraag": "Test questions number 2"
            },
            {
                "id": 3,
                "categorie": "Categorie3",
                "vraag": "Test questions number 3"
            }
        ]
        filename = 'valid_questions.json'
        with open(filename, 'w', encoding='utf-8') as f:
            json.dump(sample_data, f)
    
        # Test loading the questions
        loaded_questions = load_questions(filename)
        assert loaded_questions == sample_data
    
        # Clean up the temporary file
        os.remove(filename)

    # Handle a missing file by raising FileNotFoundError
    def test_load_questions_file_not_found(self):
        from partner_connect.main import load_questions

        # Test loading from a non-existent file
        with pytest.raises(FileNotFoundError):
            load_questions('non_existent_file.json')





